### PR TITLE
feat: :sparkles: make nav bar w/ filters responsive

### PR DESCRIPTION
**Pull request by cindyquach12**
Made nav bar w/ filters responsive and added horizontal scroll
Also modified some of the longer names in supabase so it looks better
I split up eyebrows & eyelashes so we may need to look for a lash icon to add to lashes

### CODE REVIEW

**Comment by cvogitgud** [comment]
Screen Shot 2024-06-16 at 3 33 40 PM

When zooming, the icons are pushing out of the navbar boundaries. We could make the icons themselves responsive and/or add some padding to the entire navbar.

**Review by cvogitgud — CHANGES_REQUESTED** [review]
I like the horizontal scroll on the navbar with filters, that's a nice touch. On a next pass over we could experiment with keeping the filters button visible no matter where the scroll is and see how that looks.

The only thing to address was the icon sizing when zoomed in on a smaller device.

**Comment by cindyquach12** [comment]
> Screen Shot 2024-06-16 at 3 33 40 PM
> When zooming, the icons are pushing out of the navbar boundaries. We could make the icons themselves responsive and/or add some padding to the entire navbar.

Yea I was thinking the same, I'll make them smaller on mobile!

**Review by cvogitgud — APPROVED** [review]
LGTM

**Pull request merged**
